Support Elasticsearch 5.x
Don't throw NotImplementedException in ElasticsearchSystemAdmin, that makes ES unusable as an output system in a stand-alone low-level task. Instead use the utility class SinglePartitionWithoutOffsetsSystemAdmin

org.apache.samza.SamzaException: Failed to start application: ...
Caused by: java.lang.UnsupportedOperationException: null
	at org.apache.samza.system.elasticsearch.ElasticsearchSystemAdmin.getSystemStreamMetadata(ElasticsearchSystemAdmin.java:53)
	at org.apache.samza.execution.StreamManager.getStreamPartitionCounts(StreamManager.java:97)
	at org.apache.samza.execution.ExecutionPlanner.setInputAndOutputStreamPartitionCount(ExecutionPlanner.java:197)
	at org.apache.samza.execution.ExecutionPlanner.plan(ExecutionPlanner.java:86)
	at org.apache.samza.execution.JobPlanner.getExecutionPlan(JobPlanner.java:98)
	at org.apache.samza.execution.LocalJobPlanner.prepareJobs(LocalJobPlanner.java:81)
	at org.apache.samza.runtime.LocalApplicationRunner.run(LocalApplicationRunner.java:165)
	... 14 common frames omitted